# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e4d37eee3abd29ef85b6bcf4a12d3cd000322dc428392f3807e5f9a2ca72aede5a0036d5c01bf445ee24643e1d816a27266acf7fa39983adc215341130ddac

test:
  secret_key_base: 5b2854c4872a1404d71e5d30dfe12fb7c043c1845074eb67ce0a7d6bb16503de3c229e9cfe53432ef35682595bf0e9a67bf3b2ef3208e544d33fa49a7a6af73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
